### ISSUE TITLE
Can't match trade

### ISSUE THREAD

**Issue by housemobile** [melonproject/melon-lab#240]
Trying to match trades on the orderbook.

Do the transaction, and get the following error:

**Error
Oops, something went wrong. No logs were found on the transaction receipt. Please try again.**

note: this is when using https://naxos.melon.fund

The 0.8.4 dApp doesn't even display the orderbook.

**Comment by housemobile** [comment]
Also got this error.

**Error
Cannot read property 'logs' of null**

**Comment by halcy0n9001** [comment]
Were you trying to do a limit order?

**Comment by housemobile** [comment]
Yes, clicked an order on the book.

It's possible when doing so you need to click limit, then click the order for it to work.

**Comment by housemobile** [comment]
actually that just places an equal opposite order, but doesn't execute the trade.

**Comment by jennazenk** [comment]
Thanks for the report; we'll investigate and revert back! 

The first error message (Oops, something went wrong. No logs were found on the transaction receipt. Please try again.) can happen if the order expired in the meantime.

Were you trying to take (market) or make (limit) an order? 
Limit orders only place an open order on Oasisdex ; that's why it doesn't "execute" the trade, because there needs to be a buyer taking your order @housemobile 

Regarding the app, could you give us more details mac/windows/linux ?
