### ISSUE TITLE
Hardware wallet integration

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#248]
from https://github.com/melonproject/melon-lab/issues/242

**Comment by schmidsi** [comment]
We could use this: https://frame.sh/

**Comment by jennazenk** [comment]
Yes Frame is good, but Jorge told me it's too experimental stage. 

Small note: hardware wallet integration is not enhancement it's a requirement before we release!

**Comment by schmidsi** [comment]
I removed Metamask from the title since it will be Electron only.

**Comment by schmidsi** [comment]
Hmm, I looked a bit into this. The easy Trezor integration with [Trezor Connect](https://github.com/trezor/connect) probably breaks our security assumptions of not loading anything from the internet in the renderer process. But this Trezor Connect seems to provide popups and stuff. The other possibilites, namely running Trezor's blockbook locally, would probably require strange hacks into our Electron app, since they are written in Python.

I could not find any information for Ledger, but requested access to their SDK: https://www.ledger.fr/developers/. But it will probably be similar.

But I downloaded and tried frame.sh. It is immature and is only compatible with Rinkeby and experimental with Mainnet (no kovan :( ). The UX and developer experience look nice. So my suggestion is we give it a try anyways.

Or maybe there is another library/solution out there that is more mature? I had a quick look into how MyCrypto is doing stuff but their code base is quite complex (obviously)

https://github.com/MyCryptoHQ/trezor-link
https://github.com/MyCryptoHQ/trezor.js
