### ISSUE TITLE
Add a Risk profile on fund's page

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon-lab#286]
If fund has registered policies, would be good to display them somewhere on the fund page

**Comment by schmidsi** [comment]
The problem here is to decompile the actual policies. There is no easy way to know which policy is actually behind a contract address. I see two general strategies:

a) Read the bytecode of the deployed policy and compare it with known policies
b) Add a policy identifier to the [Policy interface](https://github.com/melonproject/protocol/blob/develop/src/contracts/fund/policies/Policy.sol#L3)

A has the advantage of not changing the contracts but is much more complex to implement, whereas B would probably be easier on the front-end but also requires changes in the contract. Maybe B could also be used by other contracts?
