### ISSUE TITLE
Error when creating a new fund. 

### ISSUE THREAD

**Issue by MouyouMoos** [melonproject/melon-lab#337]
GraphQL error: Error in prepare transaction FundFactory@0xCB6c6Bdf0AA4cF0188518783b871931EFB64248f.createAccounting()): Gas estimation (preflight) failed for createAccounting(): Returned error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type *hexutil.Big

but it went through https://etherscan.io/tx/0x0af087c1b9f04b63068ec2301bace39fdd1012f4b55fdd291c809012a25ee96e. What should I do now to create my fund?

**Comment by iherger** [comment]
Hi 

Thanks for reporting this issue.

It seems that you started creating your fund, but then the creation of the `Accounting` contract failed. I guess this could be due to the fact that you don't have enough ETH in your manager account, see https://etherscan.io/address/0x45044e1ca0959ec04b92d5118b6baebfd732ae64

You should have a minimum of at least 0.1 ETH in your fund manager account before you start setting up your fund.

You started setting up your fund with the old melon manager interface. If you want to finish setting up your fund, then you need to use the same (old) melon manager interface. 

You can also set up a new fund with the latest melon manager interface, https://github.com/melonproject/melon-lab/releases/tag/v1.0.2
