### ISSUE TITLE
Error message when redeeming a fund

### ISSUE THREAD

**Issue by hjhettich** [melonproject/melon-lab#343]
Successfully redeemed a fund, very smooth transaction. However, when redeeming a second fund with exactly the same procedure, it fails. Tried it several times. Closing / re-opening the manager hasn't helped either. Error message always:
 
GraphQL error: Error in prepare transaction Participation@0x....redeemQuantity("500000000000000000")): Gas estimation (preflight) failed for redeemQuantity("500000000000000000"): Returned error: gas required exceeds allowance or always failing transaction

**Comment by hjhettich** [comment]
tried again, failed again...

**Comment by jennazenk** [comment]
We need the address of the fund so that we can debug :)

**Comment by hjhettich** [comment]
Fund 1: 0xec49dbc5e83982ab1e3bdf62dc45a3a3d0150264
Fund 2: 0x9bedb9f3e52f82413d76b15b22f780179974562e
Fund 3: 0xaf8baf75e76f274afff8c8c1399726c04a970ebb
Fund 4: 0x4d45ab206c1f1754e6d3e4d94eccb753fcfac2c2
Fund 5: 0xf5905638a9cbf16c337752ea301fa25e8af53146
Fund 6: 0xb980e1857d4dd17def4707e03bf7632f5dd95c92

Merci Jenna!

**Comment by jennazenk** [comment]
All the above funds have assets sitting in the Trading contract. Before redeeming, the manager needs to release the assets from Trading back to Vault. In order to do that, they must use the latest version of the interface 1.0.2, on the holding table you will see a "release" button next to each token that need to be released. When all assets have been release, you can then redeem
