### ISSUE TITLE
Fund list loading issue 

### ISSUE THREAD

**Issue by keef123** [melonproject/melon-lab#352]
Keep getting a "No funds are available" message when trying to view the list of funds. This often, but not always, happens after I've been using the MMI for a while (5-15 minutes). Often accompanied by a Block Overdue message. 

Frame working OK (using a Ledger Nano X or S).

MacBook Air running MacOS 10.14.6 

<img width="889" alt="Screenshot 2019-08-13 at 12 00 07" src="https://user-images.githubusercontent.com/7515425/62946573-da072e00-bdd8-11e9-9c67-dcd36cdb03a5.png">

**Comment by PR0M3TH3AN** [comment]
I'm having this issue as well. Using v1.0.2 Deb on PopOS.

**Comment by Colt21** [comment]
I'm having a similiar issue. In my case I never saw the list of funds till now on Version 1.0.3 (Same error as above).  Version 1.0.2 works well.  Ubuntu 18.04 - using the AppImage. Frame works well. Ledger Nano X.

**Comment by fubhy** [comment]
Hey there. Are you using a frame.sh with a custom RPC endpoint or are you using the default?

If not explicitly configured otherwise, Frame will first try to connect to a local node (localhost:8545), then fall back to infura. We've had issues with infura.io especially with the fund list request timing out and then failing but also with other transactions. 

If you don't have a local node or otherwise custom RPC node yourself, can you try configuring our melonport mainnet node as the custom RPC endpoint in frame.sh?

To do so, click on the top right corner (`>>>`) in your frame.sh interface, and then select "secondary" and input "https://mainnet.melonport.com" in the text field.

![Screenshot](https://user-images.githubusercontent.com/1172528/66917028-d6806500-f01c-11e9-9b9c-f0a95edccdfa.png)

**Comment by fubhy** [comment]
The fix described in my previous comment seems to have resolved the problem for the issue reporter (as reported on gitter). Closing for now. I will add a note about this to the release notes for future users until we have a full solution also for infura.io.
