### ISSUE TITLE
Whitescreen after selecting Frame

### ISSUE THREAD

**Issue by Naascap** [melonproject/melon-lab#356]
![image](https://user-images.githubusercontent.com/56631331/66905712-aaf28000-f006-11e9-9802-d9c9dc7ee06f.png)
Constantly getting a whitescreen after selecting Frame as my wallet. Unfortunately can't get past it to invest/trade in the fund I've created.

**Comment by jennazenk** [comment]
Thanks for reporting the issue - can you give some details on your OS? 
It seems you did invest in your fund though: https://monitoring.melon.network/fund?address=0x2b8410c5e551964494767ffa4225a7631d63eaa5

**Comment by Naascap** [comment]
Windows 10. I managed to invest yesterday but haven't managed to do it today.

**Comment by fubhy** [comment]
HI @Naascap. Can you try upgrading frame in case you are not on the latest version? Sometimes it also helps to restart frame entirely together with the manager interface app.

**Comment by jennazenk** [comment]
Okay that makes sense, we're getting some fair amount of error reports with Windows. That's because to be fair, none of us works on Windows so we have almost not used the Windows one. 
@fubhy will try to replicate that issue in a Windows environment. 

We'll make sure to improve the experience for Windows users, but in the meantime if you want to have a smoother experience and have access to a Mac I would totally recommend using that.

**Comment by fubhy** [comment]
Hi @Naascap can you please try the solution offered in this comment https://github.com/melonproject/melon-lab/issues/352#issuecomment-542664925 if it applies to you? Thanks!

**Comment by Naascap** [comment]
Thank you very much it seems since I've updated Frame the problem is not persisting anymore!

**Comment by fubhy** [comment]
Thanks for reporting back!
