### ISSUE TITLE
Add something like depcheck

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#7]
https://www.npmjs.com/package/depcheck

**Comment by schmidsi** [comment]
Are there other packages like this that work better in our env?

**Comment by fubhy** [comment]
I am not sure. We will have to do some research for that. And while we are on it we should also add something that ensure that we don't add any non-hoisted dependnecies (e.g. dependencies that are installed locally to individual packages because there would otherwise be a version mismatch/conflict with other packages depending on the same thing but with a different version).
