### ISSUE TITLE
Put .env files in root

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#87]
Good or bad idea?

**Comment by schmidsi** [comment]
What do you mean by simplify? I thought to just change the loading to:

```javascript
require('dotenv-extended').load({
    path: '../../.env',
    defaults: '../../.env.defaults',
    schema: '../../.env.schema',
    errorOnMissing: true,
    errorOnExtra: true,
});
```

**Comment by fubhy** [comment]
It would simplify it when you want to change your local .env file. You would just have to do it in 1 place. Not one for each service.

**Comment by schmidsi** [comment]
Don't forget to add `.env.schema` instead of `.env.example`

**Comment by fubhy** [comment]
.env.schema and .env.example are not the same. We can add a .env.schema but it's not the same as the example file. The example file is basically what you want to copy to .env and should contain local development defaults.

.env.defaults = Production defaults
.env.example = Development defaults (-> copy to .env)
.env.schema = No values, just the "required" properties (we dont' have that atm.)

**Comment by schmidsi** [comment]
Ok, I see.

But I'd rather have the development defaults in `.env.defaults` for the following reasons:
- Onboarding new developers is much easier (no extra step)
- Production env vars will be set through "real" env vars anyways

I don't know if we need a schema if there are already sane-defaults.

**Comment by fubhy** [comment]
The defaults should be the production values to make the standard environment as close to the production environment as possible for security and stability reasons (human error). We can add a Makefile step to copy the .env.example to .env in the bootstrap of the local development environment though.

Using the defaults for production values is a common practice and I don't think we should deviate from that. Also, we don't set ALL environment parameters through real env parameters on the production system. Only those that are dictated by the environment or because they contain secrets (e.g. token values, passwords, etc.). All the rest comes from the .env.defaults.
